concurrent = 4
check_interval = 0

[[runners]]
  name = "Docker Runner"
  url = "https://gitlab.com/ci"
  token = "f31QPRizyLSXj2AuH6oM"
  executor = "shell"
  builds_dir = "/home/gitlab-runner/build"
  cache_dir = "/home/gitlab-runner/cache"
  [runners.cache]

[[runners]]
  name = "Shell Runner"
  url = "https://gitlab.com/ci"
  token = "14e276dc04d55314aa2f6caa50f36b"
  executor = "shell"
  builds_dir = "/home/gitlab-runner/build"
  cache_dir = "/home/gitlab-runner/cache"
  [runners.cache]

[[runners]]
  name = "Shell Runner"
  url = "https://gitlab.com/ci"
  token = "b93748b4f290f15a82129073bfeff8"
  executor = "shell"
  builds_dir = "/home/gitlab-runner/build"
  cache_dir = "/home/gitlab-runner/cache"
  [runners.cache]
